### PR TITLE
Why not use a property instead of hardcoding the scala version?

### PR DESCRIPTION
**Pull request by calvertj**
Hey,
Why not use something like this instead of hardcoding the version?  There is probably a reason, but if not here you go,

J

### CODE REVIEW

**Comment by fnothaft** [comment]
Jenkins, add to whitelist and test this please.

**Comment by fnothaft** [comment]
Thanks for the PR, @calvertj! We used to use properties for the Scala version, but moved to [hardcode the version about a year ago](https://github.com/bigdatagenomics/utils/commit/aa0e4b6d3e8c53f6c77e650175f9a3a887ea5b19#diff-600376dffeb79835ede4a0b285078036). The backstory on this is that while using properties is arguably the right way to do things, you can't use properties and publish artifacts against multiple Scala versions. There's a long discussion of this _somewhere_... I can't find it now but it may be in #17 or https://github.com/bigdatagenomics/adam/pull/547 or https://github.com/bigdatagenomics/utils/pull/36. The short story is that if you can't have a property in any of the artifact fields, so if you parametrize the Scala version, then you can't have the Scala version in the artifact name/version, which means that you have to postprocess either your artifacts or your POMs to publish multiple Scala versions.

We wound up [postprocessing our POMs](https://github.com/bigdatagenomics/utils/blob/master/scripts/move_to_scala_2.11.sh), because it is arguably easier. I spent about a month (off and on) trying to get parameters to work, but alas, I could never find an incantation in Maven that would let us publish artifacts with parameters. However, I would be delighted to see the error in my ways—let me know if I missed anything in your PR.

Spark 2.0 is supposedly dropping Scala 2.10 support, but I think it is preferable to keep following the Scala artifact naming semantics (where the Scala major.minor version is in the artifact name), so I would prefer to keep hardcoding the version. If it's OK with you, I'll close this PR, given the history of the issue. Thank you though for opening the PR; I agree that parameters are the _right_ way to set the Scala version, unfortunately, they aren't the "correct" way. ;)

**Comment by calvertj** [comment]
I figured there was a reason,

J

**Comment by heuermh** [comment]
ok to close?

**Pull request closed without merging**
