### PR TITLE
kill `job` argument to BDGSparkCommand

### LINKED ISSUE #37: Kill `Job` argument to BDGSparkCommand
ported from / syncs with [ADAM#662](https://github.com/bigdatagenomics/adam/issues/662).

### PR DESCRIPTION
**Pull request by ryan-williams**
fixes #37 

I think this should be merge-able whenever, though the corresponding version-bump in ADAM will have to go along with the corresponding refactor over there, which I have locally built off of [ADAM#664](https://github.com/bigdatagenomics/adam/pull/664) and will file shortly, for merging whenever we're ready to actually do that upgrade, or cut a branch that includes backwards-incompatible changes from `bdg-utils-0.2.1`

### CODE REVIEW

**Comment by fnothaft** [comment]
Will merge as soon as build runs. I can cut a release after it merges, so that we can get it in to ADAM. I'll update https://github.com/bigdatagenomics/adam/pull/664 with the 0.2.1 release. Do you want to PR your changes against my https://github.com/bigdatagenomics/adam/pull/664 branch? That might be the cleanest way to do things.

**Comment by fnothaft** [comment]
Merged! Thanks @ryan-williams!

**Comment by ryan-williams** [comment]
haha, I was about to PR my changes against your #664 and apologize for the complexity of that; glad you think that is "the cleanest way" :)

I build `mvn install`d my `utils:0.2.1-SNAPSHOT` with [utils#38](https://github.com/bigdatagenomics/utils/pull/38) merged in and am building ADAM against that local `utils:0.2.1-SNAPSHOT`. As soon as that passes I'll send my PR against #664.

**Comment by fnothaft** [comment]
> haha, I was about to PR my changes against your #664 and apologize for the complexity of that; glad you think that is "the cleanest way" :)

Great minds... ;)

> I build `mvn install`d my `utils:0.2.1-SNAPSHOT` with utils#38 merged in and am building ADAM against that local `utils:0.2.1-SNAPSHOT`. As soon as that passes I'll send my PR against #664.

Sounds great. I'm starting the release process now.

**Pull request merged**
