### PR TITLE
[UTILS-77] Support Spark 2.0.0.

### LINKED ISSUE #77: Add support for Spark 2.0.0
Needed for https://github.com/bigdatagenomics/adam/issues/1093.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #77.

### CODE REVIEW

**Comment by heuermh** [comment]
Odd that the "Modifying pom.xml files to move back to Scala 2.10 for development." commit didn't happen as part of the last release.  Was there a problem with the `release.sh` script?

From the looks of things, the idea here is to keep Spark 1.x and 2.x development on master and switch between them during the release process?  Nothing jumps out at me in the code changes as conflicting with 1.x.

**Comment by fnothaft** [comment]
> Odd that the "Modifying pom.xml files to move back to Scala 2.10 for development." commit didn't happen as part of the last release. Was there a problem with the release.sh script?

Yeah, I thought that was odd too. I think that last commit has to be manually pushed. I'm guessing that it just didn't get pushed during the release process.

> From the looks of things, the idea here is to keep Spark 1.x and 2.x development on master and switch between them during the release process?

Yep, and during CI builds.

> Nothing jumps out at me in the code changes as conflicting with 1.x.

If there was, it'd cause the CI build to fail.

Jenkins failed due to a GitHub permissions issue. I just patched that, and am going to make one more Jenkins conf change (add Spark 2) and will retest.

**Comment by fnothaft** [comment]
Jenkins, retest this please.

**Comment by heuermh** [comment]
Yep, the utils release script is missing a push at the end.

See https://github.com/bigdatagenomics/adam/blob/master/scripts/release/release.sh#L76

**Comment by fnothaft** [comment]
Jenkins, test this please.

**Comment by heuermh** [comment]
Let me give this a test locally.

**Comment by heuermh** [comment]
Do we want to resolve these deprecation warnings now or later?
```
[INFO] Compiling 17 source files to utils-metrics/target/scala-2.11.4/test-classes at 1472167080436
[WARNING] utils-metrics/src/test/scala/org/bdgenomics/utils/instrumentation/MetricsListenerSuite.scala:32: warning: method accumulator in class SparkContext is deprecated: use AccumulatorV2
[WARNING]     val accumulator = sc.accumulator(0)
[WARNING]                          ^
...
```

**Comment by fnothaft** [comment]
> Do we want to resolve these deprecation warnings now or later?

I would push for later.

**Comment by heuermh** [comment]
Later it is!

**Comment by heuermh** [comment]
Thank you, @fnothaft!

**Pull request merged**
