### PR TITLE
[UTILS-114] Add abstract duplicate method to IntervalArray.

### LINKED ISSUE #114: Thread unsafe variable causing undefined/irregular behavior for ADAM
I think we should revert this back. Here are the lines in question: [Thread unsafe variable declaration](https://github.com/bigdatagenomics/utils/blob/master/utils-intervalrdd/src/main/scala/org/bdgenomics/utils/interval/array/IntervalArray.scala#L123), [Use in the get method](https://github.com/bigdatagenomics/utils/blob/master/utils-intervalrdd/src/main/scala/org/bdgenomics/utils/interval/array/IntervalArray.scala#L439). Once I took this out I no longer got the failures.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #114.

### CODE REVIEW

**Comment by heuermh** [comment]
I tested this with https://github.com/bigdatagenomics/adam/pull/1440 and it works for me locally, but of course https://github.com/bigdatagenomics/adam/pull/1360 also worked for me locally.

How should we sequence these changes?  Do we need bdg-utils newer than 0.2.11 for ADAM release 0.22.0?

**Comment by fnothaft** [comment]
> How should we sequence these changes? Do we need bdg-utils newer than 0.2.11 for ADAM release 0.22.0?

We don't _need_ it, but it'd be a nice to have due to https://github.com/bigdatagenomics/utils/pull/113.

WRT sequencing, I'd say let's merge this in here. For 0.22.0, I'm guessing you don't want to take all of the changes in https://github.com/bigdatagenomics/adam/pull/1360? If so, what I'd propose is I could then take https://github.com/bigdatagenomics/adam/pull/1440 and cut out everything _except_ for the utils bump.

**Comment by heuermh** [comment]
Agreed, #113 is worth having in 0.22.0. How about
1. merge this,
2. cut bdg-utils 0.2.13,
3. create a new pull request on ADAM with commit https://github.com/bigdatagenomics/adam/pull/1440/commits/041b4f201d1f3dfedec206c1588d27f71d006e1a updated for bdg-utils 0.2.13,
4. and then after that gets merged to ADAM I'll cleanup and squash https://github.com/bigdatagenomics/adam/pull/1360 separately for possible inclusion in 0.22.0.

**Comment by fnothaft** [comment]
I'mma slightly reorder that to:

1. merge this,
2. update adam#1440 as you said, against the snapshot
3. if all is good, cut bdg-utils 0.2.13
4. then update adam#1440 to the release
5. and then after that gets merged to ADAM @heuermh will cleanup and squash bigdatagenomics/adam#1360 separately for possible inclusion in 0.22.0.

but otherwise SGTM.

**Comment by heuermh** [comment]
+1

**Pull request merged**
