### PR TITLE
[utils-70] Generate JAR with test sources as part of release process.

### LINKED ISSUE #70: Publish test-sources jar
The bdg-utils-misc tests jar includes e.g. `SparkFunSuite`, but [there are no sources for that available in Maven central](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22org.bdgenomics.bdg-utils%22), afaict.

### PR DESCRIPTION
**Pull request by fnothaft**
Resolves #70.

### CODE REVIEW

**Comment by fnothaft** [comment]
@heuermh can I get a quick review/merge?

**Comment by heuermh** [comment]
LGTM.

Sorry for the delay, I guess I don't have proper notification on this repo.  And per #72 it looks like @jpdna doesn't have Jenkins rights.

**Comment by ryan-williams** [comment]
cool, thx! no plan to retroactively publish test-source jars for existing releases, i presume? maybe just the last one would be nice if it's easy. nbd if not.

**Comment by fnothaft** [comment]
> cool, thx! no plan to retroactively publish test-source jars for existing releases, i presume? maybe just the last one would be nice if it's easy. nbd if not.

I'm a bit slammed the next few weeks. I might be able to get to it next month, or sometime thereabouts.

**Comment by fnothaft** [comment]
> Sorry for the delay, I guess I don't have proper notification on this repo. And per #72 it looks like @jpdna doesn't have Jenkins rights.

Jenkins manages rights on a per-project basis. I'll add him.

**Pull request merged**
